Add Latrines building
Keriew/augustus pull request #1037
Opened 2024-02-02 23:43 UTC by dvincent56

Push the PR in draft
I Don't understand how it's work with editor yet so currently, latrines are not optionnal building.
Let me your comments if you see some things wrong.

2024-02-10 23:33 UTC, dvincent56 commented
Thx to @ouaz for testing.

2024-04-18 11:05 UTC, crudelios commented
Can you fix the conflicts so I can have a look at this, please?

2024-04-18 17:38 UTC, dvincent56 commented
Done

2024-04-18 22:07 UTC, Ouaz commented
Ah sorry, the french update created a conflict again ^^

2024-12-21 23:24 UTC, dvincent56 commented
Seems to crash with last unstable save files.

2025-04-30 16:05 UTC, Keriew requested changes

2025-04-30 16:05 UTC, Keriew commented on src/building/state.h
> +#define BUILDING_STATE_LATRINES (BUILDING_STATE_DYNAMIC_RESOURCES + 1)
This seems to be the problem responsible for the crash. The game needs to have enough space to assign all the values and then add one extra byte on top of that. So BUILDING_STATE_LATRINES should be BUILDING_STATE_DYNAMIC_RESOURCES + 9, the current value plus one. And then BUILDING_STATE_CURRENT_BUFFER_SIZE would currently be equal to BUILDING_STATE_LATRINES. (That one superflous constant is saved for the future backwards compatibility).

2025-04-30 23:54 UTC, dvincent56 commented
@Keriew I update and rebase the PR.

2025-05-13 09:51 UTC, merged