Update italian.c
Keriew/augustus pull request #1044
Opened 2024-02-13 18:58 UTC by berseker

Please check this updated Italian translation

2024-03-17 13:10 UTC, luigimannoni requested changes
Some changes needed mostly for whitespace and wrong round parenthesis `(` instead of braces `{`.

Translation is 100% accurate, however there are few rows to change:

- Fetching/not fetching: should have an italian translation, not sure where the string appears so my best guess should be either "Recuperando" or "Prendendo".
- "Denarii"/"Denari": New translation rows have "Denarii" some old rows have "Denari", I'd like to see "Denarii" rather than the italianization with a single plural "i". Also [wikipedia](https://it.wikipedia.org/wiki/Denario) refers it with 2 ii in the plural form which I think was the proper roman name.

2024-03-17 13:10 UTC, luigimannoni commented on src/translation/italian.c
> +	{TR_BUILDING_CONCRETE_MAKER_PRODUCTION, "La produzione è "},
Tab and whitespace at the end of string

2024-03-17 13:10 UTC, luigimannoni commented on src/translation/italian.c
> +    {TR_BUILDING_INFO_DEPOT_SELECT_SOURCE, "Scegli una fonte"},   {TR_BUILDING_INFO_DEPOT_SELECT_DESTINATION, "Scegli una destinazione"},
2 rows in the same line

2024-03-17 18:52 UTC, berseker commented
just committed a revision - thank you for the comments!

2024-03-19 10:42 UTC, luigimannoni approved these changes

2024-04-06 13:37 UTC, berseker commented
i do not know how to fix in order to merge this to master

2024-04-06 20:32 UTC, Ouaz commented
End of line 515,  there's a bracket `)` instead of a curly bracket `}`

```
src/translation/italian.c:515:70: error: expected ‘}’ before ‘)’ token
  515 |     {TR_WINDOW_ADVISOR_ENTERTAINMENT_TAVERN_COVERAGE_PLURAL,"Taverne"),
```
Add a commit to fix it, it should be good.

2024-04-07 05:16 UTC, berseker commented
> * End of line 515,  there's a bracket `)` instead of a curly bracket `}`
> 
> ```
> src/translation/italian.c:515:70: error: expected ‘}’ before ‘)’ token
>   515 |     {TR_WINDOW_ADVISOR_ENTERTAINMENT_TAVERN_COVERAGE_PLURAL,"Taverne"),
> ```
> 
> Add a commit to fix it, it should be good.
> 
> Ah, no, wait, there's more...
> 
> * Line 648: there's a break line here. The entry must be on a single line.
> 
> `{TR_BUILDING_LARGE_MAUSOLEUM_CONSTRUCTION_DESC, "Per costruire questo mausoleo` `_______ richiede materiale conservato in un magazzino, manovalanza da un campo di lavoro e architetti da una corporazione di architetti." }, `
> 
> * Line 1014: the closing `"` is missing after `azioni`
> 
> ```
> src\translation\italian.c:1014:41: error: missing terminating " character
>  1014 |     {TR_EDITOR_SCENARIO_EVENTS_ACTIONS, "azioni },
> ```
> 
> * Line 1333: the opening `"` is missing before `Porta`
> 
> `{TR_BUILDING_PANELLED_GARDEN_WALL_GATE, Porta delle mura del giardino a pannelli" },`

thank you - stupid errors which I could not see since I still do not have confidence with github editor  (is there a debug function for syntax errors?

I fixed the above points

2024-04-07 08:41 UTC, Keriew submitted a review, later dismissed
All right, looks like there's one tiny change left and then it's ready to merge.

2024-04-07 08:41 UTC, Keriew commented on src/translation/italian.c
> +	Il tuo consigliere del commercio ha ordinato di interrompere la produzione di oro."},
This line should be merged with the previous one.

2024-04-11 09:29 UTC, crudelios commented on src/translation/italian.c
> +	Il tuo consigliere del commercio ha ordinato di interrompere la produzione di oro."},
```suggestion
    {TR_BUILDING_GOLD_MINE_HALTED, "Il tuo consigliere del commercio ha ordinato di interrompere la produzione di oro."},
```

2024-04-11 09:32 UTC, merged