Adding barracks fort priority
Keriew/augustus pull request #1063
Opened 2024-03-31 19:15 UTC by dvincent56

![Barracks_UI_Mockup_copy_copy](https://github.com/Keriew/augustus/assets/81165266/2a83eed8-5df0-4475-bb76-e42bdd57b887)

2024-03-31 19:32 UTC, crudelios commented
Instead of the cart image, you have enough space to add actual text next to the checkbox, which I think would be better. Or align the cart image/ checkbox left and add the text to the right of the checkbox.

2024-03-31 20:58 UTC, dvincent56 commented
![Capture d'écran 2024-03-31 225725](https://github.com/Keriew/augustus/assets/81165266/9cd27616-a090-41b8-9955-8019682405cc)
Do you prefer the top right position like Grand Temple of Mars ?

2024-03-31 22:01 UTC, dvincent56 commented
![Capture d'écran 2024-04-01 000048](https://github.com/Keriew/augustus/assets/81165266/5d0ce85a-cded-4fba-9d5a-94a4bf20bb7b)
Remove archery button and place delivery button on top right like grand temple

2024-04-04 12:32 UTC, crudelios commented
This looks good but has merge conflicts now because of the campaign additions.

2024-04-04 19:16 UTC, dvincent56 commented
done

2024-04-04 21:48 UTC, dvincent56 commented
Areldir wants to revamp the toggle button.

2024-04-04 21:53 UTC, Areldir commented
I'm a nuisance, I know lol

2024-04-04 22:31 UTC, dvincent56 commented
I found an issue, I pass the pull request to draft
@crudelios I put comments on my problem, do you know how can I fix it without copy past the military window code in culture window ?

2024-04-10 18:43 UTC, dvincent56 commented
@crudelios Do you have an idea to fix the grand temple update instead of last barracks ?

2024-04-11 19:53 UTC, dvincent56 commented
Find a way to fix but I don't know if it's a good way.

2024-04-11 19:57 UTC, dvincent56 commented
Breaks the save ...

2024-04-12 08:37 UTC, crudelios commented on src/building/building.h
> +    unsigned char accept_delivery;
Why not just use `accepted_goods[RESOURCE_WEAPONS]`?

That way you'd avoid the entire savegame hassle.

2024-04-12 14:04 UTC, crudelios requested changes
Here are some needed changes.

Do note that there's an unfixed issue yet, on old savegames weapons will not be accepted by default.

I'm not sure how to fix that short of bumping the savegame version.

2024-04-12 14:04 UTC, crudelios commented on src/window/building_info.c
>          case 9: context.height_blocks = 20; break;
Extra tab at the end of the `case 8:` line

`case 9:` and `case 10:` lines swapped.


```suggestion
        case 8: context.height_blocks = 40; context.width_blocks = 30; break;
        case 9: context.height_blocks = 20; break;
        case 10: context.height_blocks = 47; context.width_blocks = 30; break;
```

2024-04-12 14:04 UTC, crudelios commented on src/window/building_info.c
> +    } else if (btype == BUILDING_BARRACKS ||btype == BUILDING_GRAND_TEMPLE_MARS) {
```suggestion
    } else if (btype == BUILDING_BARRACKS || btype == BUILDING_GRAND_TEMPLE_MARS) {
```

2024-04-12 14:04 UTC, crudelios commented on src/building/barracks.c
> +    int requiered_recruitment = recruit_type;
```suggestion
    int required_recruitment = recruit_type;
```

Don't forget to change the variable name elsewhere.

2024-04-12 22:09 UTC, crudelios commented
Good job!

Now either a value of `0` means the good is accepted, which is unintuitive but would work without any change, or we set another control value besides `RESOURCE_WEAPONS` (`RESOURCE_NONE` comes to mind) to `1` to signal that the current savegame is already enabling/disabling weapons.

2024-04-17 19:54 UTC, crudelios approved these changes

2024-04-17 19:54 UTC, crudelios commented
LGTM 👍

2024-04-17 19:54 UTC, merged