Add Areldir assets
Keriew/augustus pull request #129
Opened 2020-09-03 00:00 UTC by whgest

2020-09-03 09:10 UTC, crudelios requested changes

2020-09-04 15:21 UTC, whgest commented on src/map/water_supply.c
> +                strcpy(image_name, "s pond south on");
I did consider this, and I thought that relying on string ids would be less brittle than the order that assets were listed in the mod. However, your code is much cleaner and I'm realizing that strings are not used in C as much as languages I'm more familiar with.

2020-09-04 15:44 UTC, crudelios commented on src/map/water_supply.c
> +                strcpy(image_name, "s pond south on");
Indeed, C strings are messy and much slower than just using numbers or enums. This is also the way Julius works, it expects some images to be offset a specific amount from each other.

It's older coding really, but as long as the offsets are respected it's a much cleaner and more efficient way of doing things.

2020-10-21 16:38 UTC, crudelios approved these changes

2020-10-21 16:38 UTC, crudelios commented
Is this PR still needed?

2020-11-07 16:09 UTC, closed without merging