Resources stockpiling
Keriew/augustus pull request #403
Opened 2021-05-23 23:28 UTC by ipanic

- Ability to stockpile food and raw resources to the warehouse, not granary/workshop
- Ability to disable warehouse cart pusher to halt movement stockpiled resources
Updated version of this PR: https://github.com/Keriew/augustus/pull/293

2021-07-21 12:46 UTC, Keriew requested changes
Looks good codewise aside from a few small issues, could you update it to the latest build so I can merge it.

2021-07-23 13:43 UTC, ipanic commented
> Looks good codewise aside from a few small issues, could you update it to the latest build so I can merge it.

Well, I'll fix issues next week

2021-08-15 12:16 UTC, Keriew requested changes

2021-08-15 12:16 UTC, Keriew commented on src/building/building.c
> +#include "industry.h"
Please add the path to it (building/industry.h) and place it in the alphabetical order of the includes.

2021-08-15 12:16 UTC, Keriew commented on src/translation/translation.h
> +    TRANSLATION_MAX_KEY,
TRANSLATION_MAX_KEY has to be the last one.

2021-08-15 12:16 UTC, Keriew commented on src/window/building/distribution.c
> +    building* b = building_get(data.building_id);
Please attach pointer to the variable name, not to the type.

2021-08-15 12:17 UTC, Keriew commented
Looks good aside from the minor formatting issues!

2021-08-15 21:17 UTC, Keriew commented
Thanks, it's good now! 

There seems to be a conflict preventing me from merging, could you resolve it?

2021-08-19 19:27 UTC, ipanic commented
> Thanks, it's good now!
> 
> There seems to be a conflict preventing me from merging, could you resolve it?

Done

2021-08-19 23:43 UTC, Keriew approved these changes

2021-08-19 23:43 UTC, merged

2021-08-19 23:43 UTC, Keriew commented
Thanks, this will be useful!