Adding horses betting system on hippodrome
Keriew/augustus pull request #409
Opened 2021-05-25 22:34 UTC by dvincent56

- Bet on horse race from hippodrome with your personal founds
- If you loose, you loose your bet
- If you win, you double your bet, and you quadruple your bet during festivals
- During the race, your bet amount is not accessible for emperor gift of city donation.
- A notification appears at the end of the race if your horse wins the race or not.

![betting](https://user-images.githubusercontent.com/81165266/119576956-0d525b80-bdba-11eb-8ba6-483ff729a6ec.png)

2021-05-26 06:33 UTC, Riww commented
How about 50% chance for green horse to win if spring (mar,apr,jun). The same for red/summer, yellow/autumn, and white/winter. The catch could be you never know exactly when the race will end. Limit max bet and and number of bets per year to avoid unlimited funds increase. Also, 3-times bet win during no-festival, as 2 times is too much rip-off.

2021-06-16 14:42 UTC, crudelios commented
Can you fix the conflict so I can look at this, please? Thanks!

2021-06-17 18:28 UTC, dvincent56 commented
rebase done

2021-06-18 15:22 UTC, crudelios requested changes
In terms of code, just a few style changes.

Is this still crashing though?

Also, maybe a "Bet" and "Cancel" buttons?

And you shouldn't be able to change a bet after you've set one and before the race ends.

2021-06-18 15:22 UTC, crudelios commented on src/city/race_bet.c
> +}
New line at end of file

2021-06-18 15:22 UTC, crudelios commented on src/window/race_bet.c
> +
No empty first line

2021-06-18 15:22 UTC, crudelios commented on src/window/race_bet.c
> +        int id = data.focus_button_id == (i+1) || data.bet_value == (i+1) ? image_id_focus : image_id;
```suggestion
        int id = data.focus_button_id == (i + 1) || data.bet_value == (i + 1) ? image_id_focus : image_id;
```

2021-06-19 09:06 UTC, dvincent56 commented
>Also, maybe a "Bet" and "Cancel" buttons?
>And you shouldn't be able to change a bet after you've set one and before the race ends.

Agreed, I will add Bet button to confirm betting, probably not a cancel button because when you bet on race, you can't cancel your bet in real life. And asap I confirm bet, I can't change my choice.

2021-07-22 17:54 UTC, merged