Access resource settings window by right-clicking on requested resources
Keriew/augustus pull request #419
Opened 2021-06-05 14:35 UTC by sulix

It's convenient to be able to change resource settings (stockpiling, trading, etc) when managing imperial requests. For requests for resources (other than money and troops), show the resource settings window when a resource is right-clicked on in the "Emperor" advisor screen.

(Another option, if this isn't discoverable enough, would be to have a second button on the side of the resource to show this window, but the right-click option seemed simplest for now.)

The new sidebar does make this more convenient already unless (like me), the screen resolution is low enough (or scale high enough) that the requests do not display on it.

2021-06-16 14:41 UTC, crudelios commented on src/window/advisor/imperial.c
> +    if (!index && city_request_has_troop_request())
Please use braces for single-line ifs.

2021-06-16 14:42 UTC, crudelios requested changes
The code looks good, just needs a small code formatting change.

2021-06-17 10:21 UTC, sulix commented on src/window/advisor/imperial.c
> +    if (!index && city_request_has_troop_request())
Sorry — this should be fixed now.

2021-06-17 10:21 UTC, sulix commented on src/window/advisor/imperial.c
> +    if (selected_resource == RESOURCE_DENARII)
Fixed.

2021-06-17 10:22 UTC, sulix commented
Sorry about that: I've pushed a new version which fixes the braces and is rebased on top of master.

2021-06-17 15:07 UTC, crudelios commented
Just ran the game.

You must add :

```
    if (!city_request_get_status(index)) {
        return;
    }
```

To the beginning of `button_request_resource`, otherwise the game will crash when you right-click outside of a request.

2021-06-18 08:33 UTC, sulix commented
> Just ran the game.
> 
> You must add :
> 
> ```
>     if (!city_request_get_status(index)) {
>         return;
>     }
> ```
> 
> To the beginning of `button_request_resource`, otherwise the game will crash when you right-click outside of a request.

Thanks for picking that up. I've added the ``city_request_get_status()`` call, and indeed it no longer crashes.

There's still a behavioural difference in that right clicking on an empty/unused request no-longer closes the advisor panel totally.  This seems to be because the button system just checks against ``button_none`` explicitly. Personally, I kind-of prefer this behaviour, but I can look into changing it if that's required.

2021-06-18 14:49 UTC, crudelios approved these changes
Looks good now!

2021-06-18 14:49 UTC, merged