Small improvements for empire/city.c:generate_trader()
Keriew/augustus pull request #591
Opened 2022-03-26 11:09 UTC by Whiteknight

Move easy bail-out conditions up so we can deal with the cheaper conditions early
Replace the decision tree to find a free slot with a loop. This allows us to parameterize (need to adjust serialization code before we can really change these values)
Add MAX_TRADERS, SEA_TRADER_DELAY_TICKS and LAND_TRADER DELAY TICKS defines to replace some magic numbers.

2022-03-26 13:23 UTC, crudelios requested changes
Hey, some small changes, but overall a good PR 👍

2022-03-26 13:23 UTC, crudelios commented on src/empire/city.c
> +            index = f;
Shouldn't you break the loop here?

2022-03-26 13:23 UTC, crudelios commented on src/empire/city.c
> +    for (int f = 0; f < max_traders; f++) {
Nitpick: Though we use `f` for the figure pointer, for figure array indexes we do use `i`.

2022-03-26 13:23 UTC, crudelios commented on src/empire/city.h
> +#define MAX_TRADERS 3
To avoid name collisions, defines in a header should have the file name, so in this case it should be `EMPIRE_CITY_MAX_TRADERS`.

2022-03-27 00:24 UTC, crudelios approved these changes

2022-03-27 18:20 UTC, Keriew commented
These are some good changes!

2022-03-27 18:21 UTC, Keriew approved these changes

2022-03-27 18:22 UTC, merged