Cart Depot
Keriew/augustus pull request #681
Opened 2022-09-11 04:42 UTC by RuoanJi

Reopen a PR for this feature. There is another PR opened by @Whiteknight https://github.com/Keriew/augustus/pull/593 but I have made some updates since.

Details of the proposed feature can be found in the original PR https://github.com/Keriew/augustus/pull/414

2022-09-27 14:17 UTC, crudelios requested changes
Some things to fix.

Most of them are small formatting issues (I probably didn't catch them all though), but there is one or two more substancial things that I think need changing.

One of them we should discuss though, as I'm not entirely sure how to proceed.

2022-09-27 14:17 UTC, crudelios commented on src/window/building/depot.h
> +void window_building_depot_init();
```suggestion
void window_building_depot_init(void);
```

2022-09-27 14:17 UTC, crudelios commented on src/window/building/depot.c
> +static void set_order_resource(int depot_building_id, int resource_id);
The three last functions don't need a declaration. See above.

2022-09-27 14:17 UTC, crudelios commented on src/window/building/depot.c
> +static int storage_buildings_count() {
On functions, the `{` is on a different line. Also, don't forget the `void` on the paramenter list.

2022-09-27 14:17 UTC, crudelios commented on src/window/building/depot.c
> +static int storage_buildings_count() {
Also, you don't need to count all types. You can use `building_first_of_type(type)` and then increase `count` while there is a `b->next_of_type`.

2022-09-27 14:17 UTC, crudelios commented on src/window/building/depot.c
> +static scrollbar_type scrollbar = { 0, 0, ROW_HEIGHT * MAX_VISIBLE_ROWS, 432, MAX_VISIBLE_ROWS, on_scroll, 0, 4 };
Formatting: These four lines should be before any code.

2022-09-27 14:17 UTC, crudelios commented on src/window/building/depot.c
> +};
This should also go to the top.

2022-09-27 14:17 UTC, crudelios commented on src/window/building/depot.c
> +            }
Formatting: `else` on the same line.

2022-09-27 14:17 UTC, crudelios commented on src/window/building/depot.c
> +    for (int i = 1; i < building_count(); i++) {
You don't need to go through all buildings here either. See above.

2022-09-27 14:17 UTC, crudelios commented on src/window/building/depot.c
> +            }
Formatting: `else` on same line.

2022-09-27 14:17 UTC, crudelios commented on src/window/building/depot.c
> +};
To the top this goes!

2022-09-27 14:17 UTC, crudelios commented on src/window/building/figures.c
> +    building* dst = building_get(f->current_order.dst_storage_id);
Formatting (previous two lines) `building *src/dst`.

2022-10-02 03:26 UTC, RuoanJi commented on src/building/building.c
> +translation_key building_translation_key(building *b)
This is also used in `window/building/depot.c`. 

Building name translations (native and new buildings) will likely be used more in the future. I think this either resides in `building/building.h` or `translation/translation.h`. Thoughts?

2022-10-02 03:26 UTC, RuoanJi commented on src/building/building.h
> +#include "translation/translation.h"
Ack.

2022-10-02 03:27 UTC, RuoanJi commented on src/building/building.h
> +translation_key building_translation_key(building *b);
Ack

2022-10-02 03:35 UTC, RuoanJi commented on src/building/building.h
> +            order order1;
Refactored. This was added when I was unsure how many orders each depot should support.

2022-10-02 03:42 UTC, RuoanJi commented on src/figure/figure.h
> +    order current_order;
No. Once the cart leaves the depot, it is determined to fulfil its current order. The player can modify order at depot at this point, but the new order will only be picked up by the cart once it finishes/cancels its current order. A save can take place before the cart finishes current order. After loading, the cart should carry on with its current order and then start the new order.

2022-10-02 03:45 UTC, RuoanJi commented on src/figuretype/depot.c
> +#define FIGURE_REROUTE_DESTINATION_TICKS 120
I don't remember why I added this macro here, maybe it now looks conflicting due to refactoring. I guess the compiler just overwrites or ignores duplicate macro definition.

Anyway, I removed the definition here, and things still work. Great.

2022-10-02 03:50 UTC, RuoanJi commented on src/figuretype/depot.c
> +static int storage_add_resource(building *b, int resource, int amount);
I've moved the functions around to get rid of these declarations.

2022-10-02 03:52 UTC, RuoanJi commented on src/figuretype/depot.c
> +    case FIGURE_ACTION_150_ATTACK:
It looks indented on my end. This is weird, I don't think it's a tab vs space issue. Will check again after other code formatting changes.

2022-10-02 03:56 UTC, RuoanJi commented on src/figuretype/depot.c
> +static int is_order_condition_satisfied(building *depot, order *order)
Yes they both can.

2022-10-02 03:59 UTC, RuoanJi commented on src/figuretype/depot.c
> +        }
I don't remember why I did it like that, maybe I was referring to some old code that got refactored.

2022-10-02 04:22 UTC, RuoanJi commented on src/building/building.h
> +} order_condition_type;
Let's move this discussion to Discord, and the implementation will likely depend on depot mechanism. Currently either way is OK given that order and depot is 1:1 mapping. We may possibly want to change depot mechanism to 1-many or many-many.

2022-10-02 04:24 UTC, RuoanJi commented on src/translation/english.c
> +    {TR_BUILDING_WAREHOUSE, "Warehouse" },
I'll address this later.

2022-10-02 08:10 UTC, crudelios commented on src/figure/figure.h
> +    order current_order;
Makes sense!

2022-10-02 08:16 UTC, crudelios commented on src/building/building.c
> +translation_key building_translation_key(building *b)
Humm. I think it makes more sense in translation, but this way the building name is also centralised, like its image.

Right now things are done manually for every building, even on the building properties window.

For consistency sake I'd say keep this on translation (or even nowhere - just use magic values when needed, like for all other buildings).

However, your way of thinking is correct. We should centralise this. Maybe add a `lang_group` and `lang_id` to `building/properties` and fill those. This is a work for some other time though.

2022-10-02 14:22 UTC, crudelios commented
This is looking good.

The only thing left is to bump the savegame version in `src/game/file_io.c` 👍 

And add a commented `#define SAVE_GAME_LAST_VERSION_WITHOUT_CART_DEPOT <current version>` or something there, just for documentation purpose, please.

2023-02-08 21:15 UTC, crudelios commented
Closed due to updated PR on #818.

2023-02-08 21:15 UTC, closed without merging